export const ALL_SURAHS = [
  { id: 1, number: "01", nameEnglish: "Al-Fatiha", nameArabic: "الفاتحة", translation: "The Opening", verses: 7, type: "Makki", duration: "1:42" },
  { id: 2, number: "02", nameEnglish: "Al-Baqarah", nameArabic: "البقرة", translation: "The Cow", verses: 286, type: "Madani", duration: "2:05:00" },
  { id: 3, number: "03", nameEnglish: "Ali 'Imran", nameArabic: "آل عمران", translation: "Family of Imran", verses: 200, type: "Madani", duration: "1:20:00" },
  { id: 4, number: "04", nameEnglish: "An-Nisa", nameArabic: "النساء", translation: "The Women", verses: 176, type: "Madani", duration: "1:25:00" },
  { id: 5, number: "05", nameEnglish: "Al-Ma'idah", nameArabic: "المائدة", translation: "The Table Spread", verses: 120, type: "Madani", duration: "1:05:00" },
  { id: 6, number: "06", nameEnglish: "Al-An'am", nameArabic: "الأنعام", translation: "The Cattle", verses: 165, type: "Makki", duration: "1:10:00" },
  { id: 7, number: "07", nameEnglish: "Al-A'raf", nameArabic: "الأعراف", translation: "The Heights", verses: 206, type: "Makki", duration: "1:22:00" },
  { id: 8, number: "08", nameEnglish: "Al-Anfal", nameArabic: "الأنفال", translation: "The Spoils of War", verses: 75, type: "Madani", duration: "38:15" },
  { id: 9, number: "09", nameEnglish: "At-Tawbah", nameArabic: "التوبة", translation: "The Repentance", verses: 129, type: "Madani", duration: "1:02:00" },
  { id: 10, number: "10", nameEnglish: "Yunus", nameArabic: "يونس", translation: "Jonah", verses: 109, type: "Makki", duration: "48:22" },
  { id: 11, number: "11", nameEnglish: "Hud", nameArabic: "هود", translation: "Hud", verses: 123, type: "Makki", duration: "52:14" },
  { id: 12, number: "12", nameEnglish: "Yusuf", nameArabic: "يوسف", translation: "Joseph", verses: 111, type: "Makki", duration: "50:05" },
  { id: 13, number: "13", nameEnglish: "Ar-Ra'd", nameArabic: "الرعد", translation: "The Thunder", verses: 43, type: "Madani", duration: "25:40" },
  { id: 14, number: "14", nameEnglish: "Ibrahim", nameArabic: "إبراهيم", translation: "Abraham", verses: 52, type: "Makki", duration: "28:10" },
  { id: 15, number: "15", nameEnglish: "Al-Hijr", nameArabic: "الحجر", translation: "The Rocky Tract", verses: 99, type: "Makki", duration: "20:15" },
  { id: 16, number: "16", nameEnglish: "An-Nahl", nameArabic: "النحل", translation: "The Bee", verses: 128, type: "Makki", duration: "54:30" },
  { id: 17, number: "17", nameEnglish: "Al-Isra", nameArabic: "الإسراء", translation: "The Night Journey", verses: 111, type: "Makki", duration: "45:12" },
  { id: 18, number: "18", nameEnglish: "Al-Kahf", nameArabic: "الكهف", translation: "The Cave", verses: 110, type: "Makki", duration: "32:45" },
  { id: 19, number: "19", nameEnglish: "Maryam", nameArabic: "مريم", translation: "Mary", verses: 98, type: "Makki", duration: "30:15" },
  { id: 20, number: "20", nameEnglish: "Taha", nameArabic: "طه", translation: "Ta-Ha", verses: 135, type: "Makki", duration: "32:40" },
  { id: 21, number: "21", nameEnglish: "Al-Anbiya", nameArabic: "الأنبياء", translation: "The Prophets", verses: 112, type: "Makki", duration: "34:50" },
  { id: 22, number: "22", nameEnglish: "Al-Hajj", nameArabic: "الحج", translation: "The Pilgrimage", verses: 78, type: "Madani", duration: "36:12" },
  { id: 23, number: "23", nameEnglish: "Al-Mu'minun", nameArabic: "المؤمنون", translation: "The Believers", verses: 118, type: "Makki", duration: "28:15" },
  { id: 24, number: "24", nameEnglish: "An-Nur", nameArabic: "النور", translation: "The Light", verses: 64, type: "Madani", duration: "38:40" },
  { id: 25, number: "25", nameEnglish: "Al-Furqan", nameArabic: "الفرقان", translation: "The Criterion", verses: 77, type: "Makki", duration: "24:15" },
  { id: 26, number: "26", nameEnglish: "Ash-Shu'ara", nameArabic: "الشعراء", translation: "The Poets", verses: 227, type: "Makki", duration: "40:20" },
  { id: 27, number: "27", nameEnglish: "An-Naml", nameArabic: "النمل", translation: "The Ant", verses: 93, type: "Makki", duration: "30:50" },
  { id: 28, number: "28", nameEnglish: "Al-Qasas", nameArabic: "القصص", translation: "The Stories", verses: 88, type: "Makki", duration: "36:45" },
  { id: 29, number: "29", nameEnglish: "Al-'Ankabut", nameArabic: "العنكبوت", translation: "The Spider", verses: 69, type: "Makki", duration: "26:30" },
  { id: 30, number: "30", nameEnglish: "Ar-Rum", nameArabic: "الروم", translation: "The Romans", verses: 60, type: "Makki", duration: "22:15" },
  { id: 31, number: "31", nameEnglish: "Luqman", nameArabic: "لقمان", translation: "Luqman", verses: 34, type: "Makki", duration: "14:50" },
  { id: 32, number: "32", nameEnglish: "As-Sajdah", nameArabic: "السجدة", translation: "The Prostration", verses: 30, type: "Makki", duration: "10:12" },
  { id: 33, number: "33", nameEnglish: "Al-Ahzab", nameArabic: "الأحزاب", translation: "The Combined Forces", verses: 73, type: "Madani", duration: "42:15" },
  { id: 34, number: "34", nameEnglish: "Saba", nameArabic: "سبأ", translation: "Sheba", verses: 54, type: "Makki", duration: "24:10" },
  { id: 35, number: "35", nameEnglish: "Fatir", nameArabic: "فاطر", translation: "Originator", verses: 45, type: "Makki", duration: "22:45" },
  { id: 36, number: "36", nameEnglish: "Yasin", nameArabic: "يس", translation: "Ya-Sin", verses: 83, type: "Makki", duration: "22:50" },
  { id: 37, number: "37", nameEnglish: "As-Saffat", nameArabic: "الصافات", translation: "Those who set the Ranks", verses: 182, type: "Makki", duration: "28:15" },
  { id: 38, number: "38", nameEnglish: "Sad", nameArabic: "ص", translation: "The Letter Sad", verses: 88, type: "Makki", duration: "24:30" },
  { id: 39, number: "39", nameEnglish: "Az-Zumar", nameArabic: "الزمر", translation: "The Troops", verses: 75, type: "Makki", duration: "38:50" },
  { id: 40, number: "40", nameEnglish: "Ghafir", nameArabic: "غافر", translation: "The Forgiver", verses: 85, type: "Makki", duration: "38:12" },
  { id: 41, number: "41", nameEnglish: "Fussilat", nameArabic: "فصلت", translation: "Explained in Detail", verses: 54, type: "Makki", duration: "26:40" },
  { id: 42, number: "42", nameEnglish: "Ash-Shura", nameArabic: "الشورى", translation: "The Consultation", verses: 53, type: "Makki", duration: "26:15" },
  { id: 43, number: "43", nameEnglish: "Az-Zukhruf", nameArabic: "الزخرف", translation: "The Ornaments of Gold", verses: 89, type: "Makki", duration: "28:10" },
  { id: 44, number: "44", nameEnglish: "Ad-Dukhan", nameArabic: "الدخان", translation: "The Smoke", verses: 59, type: "Makki", duration: "12:50" },
  { id: 45, number: "45", nameEnglish: "Al-Jathiyah", nameArabic: "الجاثية", translation: "The Crouching", verses: 37, type: "Makki", duration: "16:45" },
  { id: 46, number: "46", nameEnglish: "Al-Ahqaf", nameArabic: "الأحقاف", translation: "The Wind-Curved Sandhills", verses: 35, type: "Makki", duration: "20:30" },
  { id: 47, number: "47", nameEnglish: "Muhammad", nameArabic: "محمد", translation: "Muhammad", verses: 38, type: "Madani", duration: "18:50" },
  { id: 48, number: "48", nameEnglish: "Al-Fath", nameArabic: "الفتح", translation: "The Victory", verses: 29, type: "Madani", duration: "18:12" },
  { id: 49, number: "49", nameEnglish: "Al-Hujurat", nameArabic: "الحجرات", translation: "The Rooms", verses: 18, type: "Madani", duration: "12:40" },
  { id: 50, number: "50", nameEnglish: "Qaf", nameArabic: "ق", translation: "The Letter Qaf", verses: 45, type: "Makki", duration: "12:55" },
  { id: 51, number: "51", nameEnglish: "Adh-Dhariyat", nameArabic: "الذاريات", translation: "The Winnowing Winds", verses: 60, type: "Makki", duration: "14:15" },
  { id: 52, number: "52", nameEnglish: "At-Tur", nameArabic: "الطور", translation: "The Mount", verses: 49, type: "Makki", duration: "12:40" },
  { id: 53, number: "53", nameEnglish: "An-Najm", nameArabic: "النجم", translation: "The Star", verses: 62, type: "Makki", duration: "11:50" },
  { id: 54, number: "54", nameEnglish: "Al-Qamar", nameArabic: "القمر", translation: "The Moon", verses: 55, type: "Makki", duration: "12:15" },
  { id: 55, number: "55", nameEnglish: "Ar-Rahman", nameArabic: "الرحمن", translation: "The Beneficent", verses: 78, type: "Madani", duration: "14:22" },
  { id: 56, number: "56", nameEnglish: "Al-Waqi'ah", nameArabic: "الواقعة", translation: "The Inevitable", verses: 96, type: "Makki", duration: "16:40" },
  { id: 57, number: "57", nameEnglish: "Al-Hadid", nameArabic: "الحديد", translation: "The Iron", verses: 29, type: "Madani", duration: "20:50" },
  { id: 58, number: "58", nameEnglish: "Al-Mujadilah", nameArabic: "المجادلة", translation: "The Pleading Woman", verses: 22, type: "Madani", duration: "14:15" },
  { id: 59, number: "59", nameEnglish: "Al-Hashr", nameArabic: "الحشر", translation: "The Exile", verses: 24, type: "Madani", duration: "15:40" },
  { id: 60, number: "60", nameEnglish: "Al-Mumtahanah", nameArabic: "الممتحنة", translation: "She that is to be examined", verses: 13, type: "Madani", duration: "14:50" },
  { id: 61, number: "61", nameEnglish: "As-Saff", nameArabic: "الصف", translation: "The Ranks", verses: 14, type: "Madani", duration: "7:12" },
  { id: 62, number: "62", nameEnglish: "Al-Jumu'ah", nameArabic: "الجمعة", translation: "The Congregation", verses: 11, type: "Madani", duration: "6:45" },
  { id: 63, number: "63", nameEnglish: "Al-Munafiqun", nameArabic: "المنافقون", translation: "The Hypocrites", verses: 11, type: "Madani", duration: "6:50" },
  { id: 64, number: "64", nameEnglish: "At-Taghabun", nameArabic: "التغابن", translation: "The Mutual Disillusion", verses: 18, type: "Madani", duration: "9:15" },
  { id: 65, number: "65", nameEnglish: "At-Talaq", nameArabic: "الطلاق", translation: "The Divorce", verses: 12, type: "Madani", duration: "8:40" },
  { id: 66, number: "66", nameEnglish: "At-Tahrim", nameArabic: "التحريم", translation: "The Prohibition", verses: 12, type: "Madani", duration: "9:10" },
  { id: 67, number: "67", nameEnglish: "Al-Mulk", nameArabic: "الملك", translation: "The Sovereignty", verses: 30, type: "Makki", duration: "6:58" },
  { id: 68, number: "68", nameEnglish: "Al-Qalam", nameArabic: "القلم", translation: "The Pen", verses: 52, type: "Makki", duration: "12:15" },
  { id: 69, number: "69", nameEnglish: "Al-Haqqah", nameArabic: "الحاقة", translation: "The Inevitable Reality", verses: 52, type: "Makki", duration: "12:40" },
  { id: 70, number: "70", nameEnglish: "Al-Ma'arij", nameArabic: "المعارج", translation: "The Ascending Stairways", verses: 44, type: "Makki", duration: "9:50" },
  { id: 71, number: "71", nameEnglish: "Nuh", nameArabic: "نوح", translation: "Noah", verses: 28, type: "Makki", duration: "8:45" },
  { id: 72, number: "72", nameEnglish: "Al-Jinn", nameArabic: "الجن", translation: "The Jinn", verses: 28, type: "Makki", duration: "8:50" },
  { id: 73, number: "73", nameEnglish: "Al-Muzzammil", nameArabic: "المزمل", translation: "The Enshrouded One", verses: 20, type: "Makki", duration: "8:40" },
  { id: 74, number: "74", nameEnglish: "Al-Muddaththir", nameArabic: "المدثر", translation: "The Cloaked One", verses: 56, type: "Makki", duration: "10:12" },
  { id: 75, number: "75", nameEnglish: "Al-Qiyamah", nameArabic: "القيامة", translation: "The Resurrection", verses: 40, type: "Makki", duration: "6:45" },
  { id: 76, number: "76", nameEnglish: "Al-Insan", nameArabic: "الانسان", translation: "The Man", verses: 31, type: "Madani", duration: "8:50" },
  { id: 77, number: "77", nameEnglish: "Al-Mursalat", nameArabic: "المرسلات", translation: "Those Sent Forth", verses: 50, type: "Makki", duration: "8:12" },
  { id: 78, number: "78", nameEnglish: "An-Naba", nameArabic: "النبأ", translation: "The Tidings", verses: 40, type: "Makki", duration: "4:36" },
  { id: 79, number: "79", nameEnglish: "An-Nazi'at", nameArabic: "النازعات", translation: "Those who drag forth", verses: 46, type: "Makki", duration: "6:40" },
  { id: 80, number: "80", nameEnglish: "'Abasa", nameArabic: "عبس", translation: "He Frowned", verses: 42, type: "Makki", duration: "4:15" },
  { id: 81, number: "81", nameEnglish: "At-Takwir", nameArabic: "التكوير", translation: "The Overthrowing", verses: 29, type: "Makki", duration: "4:12" },
  { id: 82, number: "82", nameEnglish: "Al-Infitar", nameArabic: "الانفطار", translation: "The Cleaving", verses: 19, type: "Makki", duration: "3:40" },
  { id: 83, number: "83", nameEnglish: "Al-Mutaffifin", nameArabic: "المطففين", translation: "Those Who Deal in Fraud", verses: 36, type: "Makki", duration: "6:50" },
  { id: 84, number: "84", nameEnglish: "Al-Inshiqaq", nameArabic: "الانشقاق", translation: "The Sundering", verses: 25, type: "Makki", duration: "4:10" },
  { id: 85, number: "85", nameEnglish: "Al-Buruj", nameArabic: "البروج", translation: "The Mansions of the Stars", verses: 22, type: "Makki", duration: "4:50" },
  { id: 86, number: "86", nameEnglish: "At-Tariq", nameArabic: "الطارق", translation: "The Nightcomer", verses: 17, type: "Makki", duration: "2:40" },
  { id: 87, number: "87", nameEnglish: "Al-A'la", nameArabic: "الأعلى", translation: "The Most High", verses: 19, type: "Makki", duration: "2:50" },
  { id: 88, number: "88", nameEnglish: "Al-Ghashiyah", nameArabic: "الغاشية", translation: "The Overwhelming Event", verses: 26, type: "Makki", duration: "3:45" },
  { id: 89, number: "89", nameEnglish: "Al-Fajr", nameArabic: "الفجر", translation: "The Dawn", verses: 30, type: "Makki", duration: "6:15" },
  { id: 90, number: "90", nameEnglish: "Al-Balad", nameArabic: "البلد", translation: "The City", verses: 20, type: "Makki", duration: "3:40" },
  { id: 91, number: "91", nameEnglish: "Ash-Shams", nameArabic: "الشمس", translation: "The Sun", verses: 15, type: "Makki", duration: "2:50" },
  { id: 92, number: "92", nameEnglish: "Al-Layl", nameArabic: "الليل", translation: "The Night", verses: 21, type: "Makki", duration: "3:45" },
  { id: 93, number: "93", nameEnglish: "Ad-Duha", nameArabic: "الضحى", translation: "The Morning Hours", verses: 11, type: "Makki", duration: "1:22" },
  { id: 94, number: "94", nameEnglish: "Ash-Sharh", nameArabic: "الشرح", translation: "The Relief", verses: 8, type: "Makki", duration: "1:10" },
  { id: 95, number: "95", nameEnglish: "At-Tin", nameArabic: "التين", translation: "The Fig", verses: 8, type: "Makki", duration: "1:40" },
  { id: 96, number: "96", nameEnglish: "Al-'Alaq", nameArabic: "العلق", translation: "The Clot", verses: 19, type: "Makki", duration: "2:40" },
  { id: 97, number: "97", nameEnglish: "Al-Qadr", nameArabic: "القدر", translation: "The Power", verses: 5, type: "Makki", duration: "1:20" },
  { id: 98, number: "98", nameEnglish: "Al-Bayyinah", nameArabic: "البينة", translation: "The Clear Proof", verses: 8, type: "Madani", duration: "3:15" },
  { id: 99, number: "99", nameEnglish: "Az-Zalzalah", nameArabic: "الزلزلة", translation: "The Earthquake", verses: 8, type: "Madani", duration: "1:50" },
  { id: 100, number: "100", nameEnglish: "Al-'Adiyat", nameArabic: "العاديات", translation: "The Courser", verses: 11, type: "Makki", duration: "2:10" },
  { id: 101, number: "101", nameEnglish: "Al-Qari'ah", nameArabic: "القارعة", translation: "The Calamity", verses: 11, type: "Makki", duration: "2:15" },
  { id: 102, number: "102", nameEnglish: "At-Takathur", nameArabic: "التكاثر", translation: "Competition in Increase", verses: 8, type: "Makki", duration: "1:50" },
  { id: 103, number: "103", nameEnglish: "Al-'Asr", nameArabic: "العصر", translation: "The Declining Day", verses: 3, type: "Makki", duration: "0:50" },
  { id: 104, number: "104", nameEnglish: "Al-Humazah", nameArabic: "الهمزة", translation: "The Traducer", verses: 9, type: "Makki", duration: "1:40" },
  { id: 105, number: "105", nameEnglish: "Al-Fil", nameArabic: "الفيل", translation: "The Elephant", verses: 5, type: "Makki", duration: "1:15" },
  { id: 106, number: "106", nameEnglish: "Quraysh", nameArabic: "قريش", translation: "Quraysh", verses: 4, type: "Makki", duration: "1:10" },
  { id: 107, number: "107", nameEnglish: "Al-Ma'un", nameArabic: "الماعون", translation: "Small Kindnesses", verses: 7, type: "Makki", duration: "1:40" },
  { id: 108, number: "108", nameEnglish: "Al-Kawthar", nameArabic: "الكوثر", translation: "Abundance", verses: 3, type: "Makki", duration: "0:45" },
  { id: 109, number: "109", nameEnglish: "Al-Kafirun", nameArabic: "الكافرون", translation: "The Disbelievers", verses: 6, type: "Makki", duration: "1:50" },
  { id: 110, number: "110", nameEnglish: "An-Nasr", nameArabic: "النصر", translation: "The Divine Support", verses: 3, type: "Madani", duration: "1:00" },
  { id: 111, number: "111", nameEnglish: "Al-Masad", nameArabic: "المسد", translation: "The Palm Fiber", verses: 5, type: "Makki", duration: "1:15" },
  { id: 112, number: "112", nameEnglish: "Al-Ikhlas", nameArabic: "الإخلاص", translation: "The Sincerity", verses: 4, type: "Makki", duration: "0:40" },
  { id: 113, number: "113", nameEnglish: "Al-Falaq", nameArabic: "الفلق", translation: "The Daybreak", verses: 5, type: "Makki", duration: "0:50" },
  { id: 114, number: "114", nameEnglish: "An-Nas", nameArabic: "الناس", translation: "The Mankind", verses: 6, type: "Makki", duration: "1:10" }
];
